
name: dotnetnotts app 
run-name: dotnetnotts

on: 
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  WEBAPP_NAME: bush123

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
      - name: output the github actor
        run: |
           write-host "This workflow was triggered by:${{github.actor}} "
           Write-Host "GITHUB_ACTION: $env:GITHUB_ACTION"
           Write-Host "GITHUB_ENV: $env:GITHUB_ENV"
      - name: Set Up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"  
      - name: Install Dependencies
        run: |
          
          dotnet restore .\dotnetnotts.csproj

      - name: Build Step
        run: |
          write-Host "listing files after build"
          dir
          dotnet build --configuration Debug 

      - name: Publish Step
        run: |
          dotnet publish  dotnetnotts.csproj -c Debug -o ./publish


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-artifacts
          path: ./publish/**
          if-no-files-found: error
  deploy:
      needs: build
      runs-on: windows-latest
      environment: 
        name: production
        url: ${{steps.link.outputs.webapp-url}}
      
      steps:
        - name: Download Artifact   
          uses: actions/Download-artifact@v4
          with:
            name: dotnet-artifacts
            path: it the path that the downloaded artifact will be kept 
        - name: Webdeploy step
          id: link
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{env.WEBAPP_NAME}}
            publish-profile: ${{ secrets.PRODUCTION_SECRET }}
            package: "."

        - name: display done  deploying in to azure 
          run : |
            write-host " deploy in to azure"
    


       
